name: Testing with Pytest
run-name: "Pytest on ${{ github.ref_name }} by ${{ github.actor }}"

on:
  push:
    branches: [ main ]         # add other branches if you want
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # or '3.8' if you need that

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest

      - name: Run pytest
        run: |
          PYTHONPATH=. pytest -q test --junitxml=pytest-report.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-report.xml
