name: Testing with Pytest
run-name: "Pytest on ${{ github.ref_name }} by ${{ github.actor }}"

on:
  push:
    branches:
      - main
      - 'releases/**'
  # If you don't want tests on issues/labels, delete everything below:
  # issues:
  #   types: [opened, labeled]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # or '3.8' if you need that

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest

      - name: Run tests
        run: pytest -q --junitxml=pytest-report.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-report.xml
